### PR TITLE
Connector.IBM: add projection bilan for getIBMPtsWithFront

### PR DESCRIPTION
**Pull request by BconstantMMK**

### CODE REVIEW

**Comment by vincentcasseau** [comment]
We introduced `SF_D_` to cover all int sizes so you don't have to write `%d`, `%ld` and `%lld`.
```c++
"Zone %d has %d pts"
```
becomes
```c++
"Zone " SF_D_ " has " SF_D_ " pts"
```

**Comment by antjost** [comment]
Why should ntype2 results in a warning? It is still a correct and accurate ortho projection onto the surface mesh.

**Comment by BconstantMMK** [comment]
> We introduced `SF_D_` to cover all int sizes so you don't have to write `%d`, `%ld` and `%lld`.
> 
> ```c++
> "Zone %d has %d pts"
> ```
> 
> becomes
> 
> ```c++
> "Zone " SF_D_ " has " SF_D_ " pts"
> ```

I'll remember that for future commit, thanks !

**Comment by BconstantMMK** [comment]
> Why should ntype2 results in a warning? It is still a correct and accurate ortho projection onto the surface mesh.

Fair enough, this should be changed to only look for types 2 and 3.

**Comment by antjost** [comment]
> > Why should ntype2 results in a warning? It is still a correct and accurate ortho projection onto the surface mesh.
> 
> Fair enough, this should be changed to only look for types 2 and 3.

you mean types 3 and 4?

**Comment by BconstantMMK** [comment]
> > > Why should ntype2 results in a warning? It is still a correct and accurate ortho projection onto the surface mesh.
> > 
> > 
> > Fair enough, this should be changed to only look for types 2 and 3.
> 
> you mean types 3 and 4?

yes, my bad

**Pull request merged**
