### PR TITLE
[IBM] Non-regression test case for outlet pressure control algorithm.

### PR DESCRIPTION
**Pull request by antjost**

### CODE REVIEW

**Comment by benoit128** [comment]
Salut Antoine,
Quel est le temps CPU pris par ce test et le précédent?
a+

**Comment by antjost** [comment]
Hello Christophe,
Thank you for the question. I changed some parameters and it now takes ~14s. 
I also was wondering how can we upload case cgns files needed?

**Comment by antjost** [comment]
I tried to get rid of as many case.cgns as possible. Given the length of the test case already I would prefer to not add a full geometry section also. The geometry is a 2D slice of a wind tunnel.
I brought down the time to ~6s. I think this should be good.

**Comment by benoit128** [comment]
6 secs is ok!
Can you give me access to the case.cgns file by email if possible or on /stck

**Pull request merged**
